apiVersion: apps/v1
kind: Service
metadata:
  app: nginx
  name: nginx-service
namespace: default
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
